print("Welcome to the Group Name Generator.")
Fav_Color = input("What's your favorite color?\n")
Fav_Animal = input("What is your favorite animal?\n")
# print(f"your group name could be {Fav_Color} {Fav_Animal}.")
print("Your group name could be " + Fav_Animal + " " + Fav_Color + ".")